### PR TITLE
Handle mixed types

### PR DESCRIPTION
**Pull request by tsturzl**
This project has issues handling mixed schema types, but I verified this to fix the issue.

### CODE REVIEW

**Comment by vstirbu** [comment]
Thanks for the PR!

Is this case already covered by the unit tests?

**Comment by tsturzl** [comment]
Ah, I did not. I will add it to the unit tests and let you know. I'm already using it in a project which has mixed types in the schema, so I'm fairly sure its working.

**Comment by vstirbu** [comment]
Can you post the example schema here where you use this feature. I'll add the test quickly. Thanks!

**Comment by tsturzl** [comment]
Sorry for the delayed response, I almost completely forgot about this. I added the test case. It was pretty simple. There is a mixed type(`mongoose.Schema.Types.Mixed`) you can apply to a property which essentially gives you a schema-less nested object. I added the test to `types.js` in the test, so it should be included in the test now. Take a look at my latest commit.

**Comment by vstirbu** [comment]
I'm having trouble seeing the new changes in the pull request. Noticed that the PR was made form a patch. Can you make it from the branch? Thanks!

**Comment by creynders** [comment]
@tsturzl I think you pushed your test case changes to the master branch of your fork? You should push them to the `patch-1` branch instead. @vstirbu then it should be okay.

**Comment by tsturzl** [comment]
Op, I'm a dummy. Just merged master into patch-1.

**Comment by creynders** [comment]
@tsturzl you forgot to add a test case to the test suite. Something like `expect(jsonSchema.properties. mixedProp.type).to.be.equal('object');`

**Comment by vstirbu** [comment]
PR is closed now but the content is incorporated in release [0.3.0](https://github.com/vstirbu/mongoose-jsonschema/releases/tag/0.3.0).

**Pull request closed without merging**
